links/urls.py
from django.urls import path

from .views import (start_app, import_url, import_url_success,
                    update_collection_list, change_num_columns, page_sort,
                    bookmark_sort_manual, change_collection_display,
                    check_valid_url, manual_url_scrape, links, add_bookmark,
                    arrange_collections, collection_sort, edit_bookmark,
                    move_bookmark, custom_message, update_sort_order)

urlpatterns = [
    path('_start-app',
         start_app, name="start_app"),
    path('_import-url/',
         import_url, name="import_url"),
    path('_import-url-success',
         import_url_success, name="import_url_success"),
    path('_update_collection_list',
         update_collection_list, name="update_collection_list"),
    path('_change-num-columns/<page>/<num>',
         change_num_columns, name="change_num_columns"),
    path('_page_sort',
         page_sort, name="page_sort"),
    path('_bookmark_sort_manual',
         bookmark_sort_manual, name="bookmark_sort_manual"),
    path('_change_collection_display',
         change_collection_display, name="change_collection_display"),
    path('_check_valid_url',
         check_valid_url, name="check_valid_url"),
    path('_manual_url_scrape',
         manual_url_scrape, name="manual_url_scrape"),

    path('<page>', links, name="links"),

    path('<page>/add-bookmark',
         add_bookmark, name="add_bookmark"),
    path('<page>/arrange',
         arrange_collections, name="arrange_collections"),
    path('<page>/collection-sort',
         collection_sort, name="collection_sort"),
    path('<page>/<bookmark>/edit-bookmark',
         edit_bookmark, name="edit_bookmark"),
    path('<page>/<bookmark>/move-bookmark',
         move_bookmark, name="move_bookmark"),
    path('<page>/custom_message/<message>',
         custom_message, name="custom_message"),
    path('<page>/<collection>/<sort>/update_sort_order',
         update_sort_order, name='update_sort_order'),
    path('', start_app, name="start_app"),
]

main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from pages.views import about, pricing, faq

urlpatterns = [
    # paths for pages
    path('', about, name="about_page"),
    path('pricing', pricing, name="pricing_page"),
    path('faq', faq, name="faq_page"),
    # path for links app
    path('app/', include('links.urls')),
    # path for search app
    path('search/', include('search.urls')),
    # paths for accounts
    path('accounts/', include('accounts.urls')),
    # paths for admin
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

links/models.py
from django.conf import settings
from django.core.files.storage import default_storage
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models

from .validators import validate_icon_file_extension, validate_icon_file_size

from PIL import Image

User = settings.AUTH_USER_MODEL


class Page(models.Model):
    """
    A page is a single view for the user that contains a number of
    collections.
    Stores settings for how those collections should be displayed.
    """
    user = models.ForeignKey(
        User, default=1, null=False, on_delete=models.CASCADE
    )
    name = models.CharField(
        max_length=30, null=False, blank=False
    )
    position = models.PositiveIntegerField(
        null=False, blank=False
    )
    position_temp = models.PositiveIntegerField(
        null=True, blank=True
    )
    num_of_columns = models.PositiveIntegerField(
        default=4, validators=[MinValueValidator(1), MaxValueValidator(5)]
    )
    collection_order_2 = models.TextField(
        null=True, blank=True
    )
    collection_order_3 = models.TextField(
        null=True, blank=True
    )
    collection_order_4 = models.TextField(
        null=True, blank=True
    )
    collection_order_5 = models.TextField(
        null=True, blank=True
    )

    class Meta:
        unique_together = [['position', 'user'], ['name', 'user']]

    def __str__(self):
        return self.name


class Collection(models.Model):
    """
    A collection is a grouping of Bookmark objects.
    The collection will store data on its position within the page and
    also on how the bookmarks within should be displayed.
    """
    user = models.ForeignKey(
        User, default=1, null=False, on_delete=models.CASCADE
    )
    page = models.ForeignKey(
        Page, default=1, null=False, on_delete=models.CASCADE
    )
    name = models.CharField(
        max_length=30, null=False, blank=False
    )
    position = models.PositiveIntegerField(
        null=False, blank=False
    )
    position_temp = models.PositiveIntegerField(
        null=True, blank=True
    )
    display_mode = models.PositiveIntegerField(
        default=1, validators=[MinValueValidator(1), MaxValueValidator(3)],
        null=False, blank=True
    )
    sort_order = models.PositiveIntegerField(
        default=0, validators=[MinValueValidator(0), MaxValueValidator(6)],
        null=False, blank=True
    )

    class Meta:
        unique_together = [['name', 'user', 'page'],
                           ['position', 'name', 'page', 'user']]

    def __str__(self):
        return self.name

    def collection_name(self):
        return self.name

    collection_name.short_description = "Collection Name"


def icon_location(instance, filename):
    return "icons/{}/{}".format(instance.user.username.lower(), filename)


class Bookmark(models.Model):
    """
    A Bookmark is a object that stores data for a single Bookmark
    entity.
    As well as basic data such as name, title, icon etc, it will also
    keep track of its position within its parent Collection.
    """
    user = models.ForeignKey(
        User, default=1, null=False, on_delete=models.CASCADE
    )
    collection = models.ForeignKey(
        Collection,
        default=1, null=False, blank=False,
        on_delete=models.CASCADE, related_name='bookmarks'
    )
    url = models.URLField(
        null=False, blank=False
    )
    title = models.CharField(
        max_length=255, null=False, blank=False
    )
    description = models.CharField(
        max_length=500, null=True, blank=True
    )
    icon = models.ImageField(
        upload_to=icon_location, null=True, blank=True,
        validators=[validate_icon_file_extension, validate_icon_file_size]
    )
    added = models.DateTimeField(
        auto_now_add=True
    )
    updated = models.DateTimeField(
        auto_now=True
    )
    position = models.PositiveIntegerField(
        null=False, blank=True
    )
    position_temp = models.PositiveIntegerField(
        null=True, blank=True
    )

    class Meta:
        unique_together = ['collection', 'position']

    def __str__(self):
        return self.url

    def bookmark_page(self):
        page = Page.objects.get(
            collection=self.collection
        )
        return page.name

    def save(self, *args, **kwargs):
        # handle images on save
        super(Bookmark, self).save(*args, **kwargs)
        if self.icon:
            im = Image.open(self.icon)
            px_size = 128
            # resize image if too large
            if im.height > px_size or im.width > px_size:
                new_im = im.resize((px_size, px_size))
                tmp = default_storage.open(self.icon.name, 'wb')
                new_im.save(tmp)
                tmp.close()
                im.close()


class MoveBookmark(models.Model):
    """
    Used with MoveBookmarkForm to allow the user to choose the
    destination Page / Collection when moving Bookmark objects.
    """
    dest_page = models.ForeignKey(
        Page,
        default=1, null=False, blank=False, on_delete=models.CASCADE
    )
    dest_collection = models.ForeignKey(
        Collection,
        default=1, null=False, blank=False, on_delete=models.CASCADE
    )

links/forms.py
from django import forms

from .models import Page, Collection, Bookmark, MoveBookmark

import re


class PageForm(forms.ModelForm):
    """ PageForm template, can be subclassed by other page forms """
    class Meta:
        model = Page
        fields = ['name']

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('current_user')
        super(PageForm, self).__init__(*args, **kwargs)

    def clean_name(self):
        name = self.cleaned_data.get('name')

        # check the page name is unique to that user
        if Page.objects.filter(user=self.user, name__iexact=name):
            raise forms.ValidationError(
                u'You already have a page with this name')

        # check the page name against a list of reserved names
        reserved_name_list = []  # Add names as / if required
        if name in reserved_name_list:
            raise forms.ValidationError(
                u'Sorry, that name is reserved. Please choose a different one')

        # check page name contains only allowed chars
        allowed_chars = re.compile(r'[^-: a-zA-Z0-9.]')
        char_check = allowed_chars.search(name)
        if char_check:
            raise forms.ValidationError(
                u"Name can only contain letters, numbers, \
                            spaces, hyphens '-', and colons ':'")

        return name


class AddNewPageForm(PageForm):
    """ Form for adding a new page """

    # user choices for how many columns a new page should start with
    NUM_COLUMN_CHOICES = (
        (1, 1),
        (2, 2),
        (3, 3),
        (4, 4),
        (5, 5),
    )

    num_of_columns = forms.ChoiceField(
        initial=4, label="Columns", choices=NUM_COLUMN_CHOICES
    )

    class Meta:
        model = Page
        fields = ['name', 'num_of_columns']


class EditPageForm(PageForm):
    """ Form used to edit an existing page """
    class Meta:
        model = Page
        fields = ['name']

    def __init__(self, *args, **kwargs):
        super(EditPageForm, self).__init__(*args, **kwargs)
        self.fields['name'].label = "New Page Name"


class BookmarkForm(forms.ModelForm):
    """ Form for creating a new Bookmark object """

    description = forms.CharField(
        widget=forms.Textarea(attrs={'rows': 5})
    )

    class Meta:
        model = Bookmark
        fields = ['url', 'title', 'description', 'icon']


class MoveBookmarkForm(forms.ModelForm):
    """ Form used to move a bookmark to a new page / collection """

    class Meta:
        model = MoveBookmark
        fields = ['dest_page', 'dest_collection']

    def __init__(self, user, page, *args, **kwargs):
        super(MoveBookmarkForm, self).__init__(*args, **kwargs)
        self.fields['dest_page'].queryset = Page.objects.filter(
            user=user).order_by('position')
        self.fields['dest_collection'].queryset = Collection.objects.filter(
            user=user, page=page).order_by('position')
        self.fields['dest_collection'].error_messages = {
            'required': "Bookmarks cannot be in a page with no collections, \
                please choose a page with at least one collecion"
            }
        self.fields['dest_page'].label = "Destination Page"
        self.fields['dest_collection'].label = "Destination Collection"

links/templates/links/components/add_new_collection.html
{% if not no_collections %}
<div class="text-center">
    <button class="btn--add-collection mt-4"><i class="fa fa-plus-circle fa-2x tippy-add-new-collection" aria-hidden="true"></i></button>
</div>

<div id="add-collection-{{ column }}" class="display-toggle text-center">
    <form method="POST" class="add-collection p-2">
        {% csrf_token %}
        <small>New Collection Name</small><br />
        <input type="hidden" name="column" value="{{column}}">
        <input type="hidden" name="is_empty" value="{{is_empty}}">
        <input type="text" name="collection_name" class="w-100"><br />
        <input type="submit" name="add-collection" value="Add Collection" class="btn--standard btn-sm my-2">
    </form>
</div>
{% endif %}

links/templates/links/components/bookmark_delete_modal.html
<div class="modal fade" id="modal-bm-{{ bookmark }}" tabindex="-1" role="dialog" aria-labelledby="bookmark-delete-modal"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form method="POST">
                <div class="modal-header">
                    <h4 class="mb-0"><i class="fa fa-stop mr-2" aria-hidden="true"></i>Delete Bookmark</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>Are you sure you want to delete </p>
                    <h6 class="delete-modal-item text-trunc"><i class="fa fa-dot-circle-o"
                            aria-hidden="true"></i>{{ url }}</h6>
                    <p>This action cannot be reversed and the bookmark will be permanently deleted.
                    </p>
                    {% csrf_token %}

                    <input type="hidden" name="bookmark" value="{{ bookmark }}">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn--faded" data-dismiss="modal">Cancel</button>
                    <input type="submit" name="delete-bookmark-form" value="DELETE" class="btn--delete">
                </div>
            </form>
        </div>
    </div>
</div>

links/templates/links/components/bookmark_dest_form.html
{% load crispy_forms_tags %}

<!-- bookmark destination form -->
<div class="row mt-3">
    {% for field in move_bookmark_form %}
    <div class="col-12 col-xl-6">
        {{ field|as_crispy_field }}
    </div>
    {% endfor %}
</div>

links/templates/links/components/bookmark_form.html
{% load crispy_forms_tags %}

<!-- bookmark form -->
{% for field in bookmark_form.visible_fields %}
    {% if field.label != 'Icon' %}
        <!-- text fields -->
        <div>{{ field|as_crispy_field }}</div>
        {% if field.label == 'Url' %}
            <div class="url-validation-wrapper">
                <small id="url-validation-result" class="">Url status: <span class="status status-valid">Valid</span></small>
                <span class="fa-stack tippy-i tippy-url-validation cursor-pointer">
                    <i class="fa fa-square fa-stack-2x" aria-hidden="true"></i>
                    <i class="fa fa-info fa-stack-1x fa-inverse" aria-hidden="true"></i>
                </span>
            </div>
        {% endif %}
    {% else %}
        <!-- icon field -->
        <div class="mb-2">Icon</div>
        <div class="custom-file">
            <input type="file" accept=".png, .jpg, .jpeg, .ico" name="icon" class="custom-file-input" id="id_icon">
            <label class="custom-file-label {% if field.errors %}icon-field-errors{% endif %}" for="id_icon">Choose file</label>
            <div class="list-unstyled icon-errors">{{ field.errors|striptags }}
            </div>
        </div>
    {% endif %}
{% endfor %}

<div>
    <small>Upload your own, use autofill to get the site icon directly, or allow
        the app to create one for you.</small>
</div>

links/templates/links/components/delete_modal.html
<div class="modal fade" id="{{ id }}" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form method="POST">
                <div class="modal-header">
                    <h4 class="mb-0"><i class="fa fa-stop mr-2" aria-hidden="true"></i>Delete {{ params.object_type|title }}</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>Are you sure you want to delete </p>
                    <h6 class="delete-modal-item text-trunc"><i class="fa fa-dot-circle-o"
                            aria-hidden="true"></i>{{ object }}</h6>
                    <p>This action cannot be reversed and {{ params.text }} </p>
                    {% csrf_token %}

                    <input type="hidden" name="{{ params.object_type }}" value="{{ item_to_delete }}">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn--faded" data-dismiss="modal">Cancel</button>
                    <input type="submit" name="{{ params.form_name }}" value="DELETE" class="btn--delete">
                </div>
            </form>
        </div>
    </div>
</div>

links/templates/links/components/sidebar_links.html
{% load staticfiles %}

{% load crispy_forms_tags %}

<nav id="sidebar">

    <!-- sidebar toggle button -->
    <div class="sidebarToggle d-inline d-md-none">
        <i class="fa fa-bars ml-2 mt-1 pl-4 pt-3"></i>
    </div>

    <!-- site logo -->
    <div>
        <a href="{% url 'start_app' %}">
            <img class="logo" src="{% static 'img/logo/logo_circle_200.png' %}" alt="">
        </a>
    </div>

    <!-- Add Bookmark button -->
    <div class="add-bm-btn-sidebar text-center mb-5">
        <a href="{% url 'add_bookmark' page=page %}">
            <h5 class="text-center"><i class="fa fa-plus" aria-hidden="true"></i>Add Bookmark</h5>
        </a>
    </div>

    <div id="page-options" class="row mx-0">
        <div class="col-12 p-0">
            <!-- list all user pages -->
            <h5 class="ml-4 d-inline-block"><span>Pages</span></h5>
            {% if bm_data %}

            <div class="float-right">
                <!-- display page sort button if on main app page - ie not arrange, add, edit, etc -->
                <button id="page-sort-btn"
                    class="btn--page-options mr-2 {% if page_sort_active %}page-sort-active{% endif %}"><i
                        class="fa fa-sort" aria-hidden="true"></i></button>
                <!-- add new page button -->
                <button id="add-page-btn" class="btn--page-options mr-4"><i class="fa fa-plus"
                        aria-hidden="true"></i></button>
            </div>
            <!-- add new page form -->
            <div id="add-page-form-wrapper" class="mx-4">
                <form method="POST" class="add-page-form mx-3" {% if add_new_page_form.errors %} style="display: block;"
                    {% endif %} novalidate>
                    {% csrf_token %}
                    <h6>Add New Page</h6>
                    {{ add_new_page_form|crispy }}
                    <input type="submit" value="Add Page" name="add-page-form" class="btn--standard mt-1 mb-3">
                </form>
            </div>
            {% endif %}
        </div>
    </div>

    <div class="mx-2 my-2">
        <ul id="page-titles" class="list-unstyled">
            {% for name in all_page_names %}
            <!-- individual page titles -->
            <li id="{{name.position}}_." class="{% if name.name == page %}active{% endif %}">
                <!-- handle & icon for sorting page display order -->
                <div class="clearfix page-sort-handle-container {% if page_sort_active %}page-sort-handle{% endif %}">
                    <div class="float-left my-2 ml-2 page-sort-icon-container
                        {% if not page_sort_active %}
                            hide-page-sort-icon
                        {% endif %}">
                        <i class="fa fa-ellipsis-v" aria-hidden="true" {% if name.name == page %}style="color: black"
                            {% endif %}></i>
                    </div>
                    <!-- page title & icons -->
                    <a class="nav-link float-left page-name" href="{% url 'links' page=name %}">{{name}}</a>
                    {% if name.name == page %}
                        {% if bm_data %}
                        <div class="float-right my-2 mr-3">
                            <a href="#"><i id="page-options-btn" class="fa fa-cog text-dark page-options-btn" aria-hidden="true"></i></a>
                        </div>
                        {% endif %}
                    {% endif %}

                </div>

                <!-- edit page form -->
                {% if name.name == page %}
                <div id="page-display-options" {% if edit_page_form.errors %} style="display: block;" {% endif %}>
                    <div class="d-flex flex-column mt-3 mb-4">
                        <div class="ml-3 mb-1">
                            <a href="{% url 'arrange_collections' page=page %}" class="btn--standard btn-sm"
                                role="button">Arrange Collections</a>
                        </div>
                        <!-- section to choose number of columns - temp -->
                        <div class="ml-3">
                            <div>
                                <small class="text-dark">Columns</small>
                            </div>
                            {% with ''|center:5 as range %}
                            {% for _ in range %}
                            <a class="{% if forloop.counter == num_of_columns %}btn--white{% else %}btn--standard{% endif %} btn-sm"
                                href="{% url 'change_num_columns' page=page num=forloop.counter %}"
                                role="button">{{ forloop.counter }}</a>
                            {% endfor %}
                            {% endwith %}
                        </div>
                    </div>
                    <form method="POST" class="edit-page-form px-3 pb-3" novalidate>
                        {% csrf_token %}
                        {{ edit_page_form|crispy}}
                        <div class="mt-n2">
                            <input type="submit" value="Rename" name="edit-page-form" class="btn--standard">
                            <input type="button" value="Delete" class="btn--delete ml-2 float-right" data-toggle="modal"
                                data-target="#page-delete-modal">
                        </div>
                    </form>
                </div>

                {% endif %}
            </li>
            {% endfor %}
        </ul>
    </div>

    <!-- display premium badge -->
    {% if is_premium %}
    <div class="my-5 text-center">
        <div class="d-flex justify-content-center">
            <h1><span class="badge badge-dark">PREMIUM</span></h1>
        </div>
    </div>
    {% endif %}
</nav>

<!-- page delete modal -->
{% include 'links/components/delete_modal.html' with id="page-delete-modal" object=page params=page_delete_modal %}